### PR TITLE
OneSignal improvements

### PR DESCRIPTION
**Pull request by Inoverse**
Two OneSignal changes:
* Changed init function to support notificationOpenedCallback as an optional parameter
* Removed platform specification

### CODE REVIEW

**Comment by ihadeed** [comment]
Hey there,

Why did you change the Promise to a Callback?

Is it because that callback gets triggered multiple times? If that's the case we can convert the return type to an Observable instead.

**Comment by Inoverse** [comment]
Hi,

yes it's not trigged during the application run. It's triggered when a notification was received, which can be occures multiple times. Observable could be a solution.

**Comment by ihadeed** [comment]
`@Corova({
  observable: true
})
static methodName(): Observable<any> {return; }
`

**Comment by Inoverse** [comment]
Changed it to an observable.

**Comment by ihadeed** [comment]
thanks

**Pull request merged**
