### PR TITLE
Update devicemotion.ts

### PR DESCRIPTION
**Pull request by cfjedimaster**
Fix typo in code comments which led to wrong docs.

### CODE REVIEW

**Comment by ihadeed** [comment]
You have an extra character added by accident on line 5

**Comment by cfjedimaster** [comment]
fixed - thanks!

**Comment by ihadeed** [comment]
Oh.. I apologize @cfjedimaster I just realized that Mike (of ionic) has modified these docs here: https://github.com/driftyco/ionic-native/commit/4a38c02c14d6947a2475ba8bc6f40ad47589e8ac

I think we are no longer keeping method specific docs, all docs are placed in the `@usage` section of the `@Plugin` decorator.

Thanks anyways for the PR! Your efforts are appreciated!

**Comment by cfjedimaster** [comment]
Isn't that what I changed though?

**Comment by ihadeed** [comment]
The code that you changed is no longer included in that part of the docs.

**Comment by cfjedimaster** [comment]
Ah ok - gotcha.

**Pull request closed without merging**
