### PR TITLE
feat(crop): add crop plugin

### PR DESCRIPTION
**Pull request by ihadeed**
This plugin doesn't seem very stable, but we can add it if it's something people want.

Will leave this PR here and if we get lots of +1s we'll merge.

Repo is here: https://github.com/jeduan/cordova-plugin-crop

### CODE REVIEW

**Comment by mlynch** [comment]
Seems like a useful plugin, but I haven't tested it myself. You have my vote

**Comment by marcinwadon** [comment]
@ihadeed, @mlynch: Yup, it could be useful in some cases, but official repo has still a lot of bugs.

**Comment by ihadeed** [comment]
Tested on *Android 5* device, works great.

I'll try to test on other devices when I get a chance. If anyone has any results please post here.

**Comment by marcinwadon** [comment]
Tested on Huawei P8 Lite (Android 6.0) and works great also.

**Comment by mlynch** [comment]
I say let's merge and we can iterate

**Pull request merged**
