### PR TITLE
docs(template): Improved plugin docs

### PR DESCRIPTION
**Pull request by piotrowski**
This PR makes it clear that installation is a two step process of 1) running commands on the CLI and 2) "Add this plugin to your app's module" (which links to the explanation in the Ionic Native Overiew at https://ionicframework.com/docs/native/#Add_Plugins_to_Your_App_Module). It also switches the plugin description with the installation commands.

This way users that "miss" this part of the docs will have a better Ionic Native experience and I hope most of the "This Ionic Native plugin is not working and throwing this strange error" posts in the forum will go away.

Currently:

bildschirmfoto am 2017-05-05 um 13 36 37

After this PR is accepted and docs regenerated:

bildschirmfoto am 2017-05-05 um 13 36 45

### CODE REVIEW

**Comment by piotrowski** [comment]
I am not 100% sure about the `<style>` block, any better way to fix the styling of the `ol li`?

Next steps and possible future PRs include improvements on all the plugins' descriptions that are now more highlighted or improvements on the "Add Plugins to Your App's Module" paragraph of the Overview that will now get more readers. The whitespace of headlines could also be minimized, I am currently investigating if this is needed anywhere else.

**Comment by ihadeed** [comment]
CC: @perrygovier

**Comment by perrygovier** [comment]
Hey @piotrowski, looks good to me, but I added the styles to ionic-site directly. Could you remove the inline styles from this PR? Then I think it's ok to merge

**Comment by piotrowski** [comment]
Thanks. Removed them, so I think we are good to go.

**Comment by danielsogl** [comment]
@perrygovier we should also add the new CLI 3.x `ionic cordova plugin add ...` command

**Comment by piotrowski** [comment]
Good point, I added this. I started this PR before CLI3 came out.

**Comment by piotrowski** [comment]
@perrygovier Do you need anything else changed here or can this be merged now?

**Comment by piotrowski** [comment]
Hmmm:
https://github.com/driftyco/ionic-site/blob/master/content/docs/native/camera/index.md looks good, but https://ionicframework.com/docs/native/onesignal/ is some other version that is missing the "Installation" bit and also has wrong order of repo vs. description.

**Comment by ihadeed** [comment]
@piotrowski it's not published to production yet .. see http://ionic-site-staging.herokuapp.com/docs/native/onesignal/

**Comment by piotrowski** [comment]
D'oh me. Sorry.

**Pull request merged**
