### PR TITLE
Reformat to match guidelines (WIP)

### PR DESCRIPTION
**Pull request by ZiFFeL1992**

### CODE REVIEW

**Comment by mlynch** [comment]
@ZiFFeL1992 is this the result of running the tslint rules from PR #276?

**Comment by ZiFFeL1992** [comment]
Order imports alphabetically, use spaces in imports like angular and 2 spaces (tabs) as stated in the .editorconfig.

I'm in vacation right now, if you will merge this when I finish I'll continue this when I come back.

**Comment by ihadeed** [comment]
@ZiFFeL1992 I left you a message on Slack saying that whenever you get a chance to fix the conflicts let me know, so I will keep the master branch untouched to prevent further conflicts.

**Comment by ZiFFeL1992** [comment]
@ihadeed you can change whatever you need, I'll fix and complete the PR when I come back.

**Pull request merged**
