### PR TITLE
Improvements socialsharing

### PR DESCRIPTION
**Pull request by ramonornela**
- Improvements docs;
- Fix order callback because params are optional;
- Feature add method shareVia();
- Feature add params optionals canShareVia().

### CODE REVIEW

**Comment by ZiFFeL1992** [comment]
Hey! Thanks for this PR, have you been able to remove the delays while sharing? I'm actually using socialsharing without the wrapper...

**Comment by ramonornela** [comment]
@ZiFFeL1992 continue delay, attempt try work it later ;), thanks by report.

**Comment by ihadeed** [comment]
@ZiFFeL1992 I'm experiencing delays too, but they occur while using the original plugin API as well. It usually happens the first time the user tries to share something after launching the app.

**Comment by ihadeed** [comment]
thanks for the PR @ramonornela

**Comment by ramonornela** [comment]
@ihadeed  Sorry missing comma in the key errorIndex ;), i should have run `npm run build`

**Pull request merged**
