### PR TITLE
chore(tslint-rules): Use ionic-tslint-rules

### LINKED ISSUE #289: Improvement to tslint.json
Change [tslint.json](https://github.com/driftyco/ionic-native/blob/master/tslint.json) to extends and use [tslint-ionic-rules](https://github.com/driftyco/tslint-ionic-rules)

### PR DESCRIPTION
**Pull request by ZiFFeL1992**
closes #289

### CODE REVIEW

**Comment by mlynch** [comment]
I know @ihadeed set up the tslint stuff so will let him chime in. However, we are starting to use those rules for all our TS projects so this looks good to me on paper.

**Comment by ZiFFeL1992** [comment]
This is ready for merge as well, @ihadeed .

**Comment by ZiFFeL1992** [comment]
I followed the steps of Brandy on this commit: https://github.com/driftyco/ionic-conference-app/commit/1b81cf22b7a8ebf584857b5891a56e91efcb240a

**Comment by ihadeed** [comment]
thanks

**Pull request merged**
