### PR TITLE
Implemented wrappers for FileTransfer.

### PR DESCRIPTION
**Pull request by glecaros**
Added wrappers for the file transfer plugin.

### CODE REVIEW

**Comment by royipressburger** [comment]
Hi cool plugin!

Does the PR expose the `onprogress` method?

**Comment by glecaros** [comment]
hey, totally missed that, will update tonight

**Comment by ihadeed** [comment]
Hey @glecaros 
Just looking at this now.

How about we implement the new instance wrapper that we have for Ionic Native?

So instead of the `ft` property you have, add a `_objectInstance` property. Then remove any functionality from the instance methods and just add `@CordovaInstance()` decorator to them.

I think this would be a good example to follow: https://github.com/driftyco/ionic-native/blob/master/src/plugins/media.ts

Let me know if you have any questions of suggestions.

Thanks for your efforts.

**Comment by glecaros** [comment]
ok, I'll look into that

**Comment by ihadeed** [comment]
-- For reference, this PR will close #70 if merged.

**Comment by glecaros** [comment]
I've updated to use the CordovaInstance (also rebased to latest master)
I had to change the signature of the wrapInstance method since the parameters didn't match how it was being called.

**Comment by djangojack** [comment]
@glecaros @ihadeed is this rdy to merge?

**Comment by ihadeed** [comment]
Thanks @glecaros

**Comment by glecaros** [comment]
Cool, thanks!

**Pull request merged**
