### PR TITLE
fix(diagnostic): Some fixes regarding objects

### PR DESCRIPTION
**Pull request by ZiFFeL1992**
Code formatting as well.

### CODE REVIEW

**Comment by ZiFFeL1992** [comment]
WIP don't merge please.

**Comment by ZiFFeL1992** [comment]
This should be able to merge but I'm not sure if `permissionGroups` is okay.

**Comment by ZiFFeL1992** [comment]
I have review `permissionGroups` and looks fine, also fix a little typo, you can merge this @ihadeed .

**Comment by ihadeed** [comment]
thanks

**Pull request merged**
