### PR TITLE
feat(sim): add new methods

### PR DESCRIPTION
**Pull request by pbakondy**
Add hasReadPermission and requestReadPermission to cordova-plugin-sim

### CODE REVIEW

**Comment by ihadeed** [comment]
thanks

**Comment by pbakondy** [comment]
Hi, the docs page did not change, please check
https://ionicframework.com/docs/v2/native/sim/

**Comment by ihadeed** [comment]
The official docs get updated manually and they haven't been updated yet.

They are up to date on the staging site: http://ionic-site-staging.herokuapp.com/docs/v2/native/sim/

**Comment by pbakondy** [comment]
Good to know, thanks

**Pull request merged**
