### PR TITLE
fix(googlemaps): typo in GoogleMapsTileOverlayOptions

### PR DESCRIPTION
**Pull request by SylvainGuittard**
related to my first PR (https://github.com/driftyco/ionic-native/pull/580) and this issue: https://github.com/driftyco/ionic-native/issues/579

The commit (https://github.com/driftyco/ionic-native/commit/f36b1c03cbaed2ddc71d4cbd02d55959d2267258) does not fix the issue.

### CODE REVIEW

**Comment by ramonornela** [comment]
Since the first version exists typo https://github.com/driftyco/ionic-native/blob/55a7f1f3774d834803b5fc09648a01fd78e173c2/src/plugins/googlemaps.ts we have to test suite with urgently

Thanks

**Comment by SylvainGuittard** [comment]
@ramonornela How can I help you?  Unit tests?

**Comment by ramonornela** [comment]
Try to works in an proposal later @SylvainGuittard , after integration this has need effort to write tests all

Thanks

**Comment by ihadeed** [comment]
thanks!

**Pull request merged**
