### PR TITLE
add network plugin for issue #89

### PR DESCRIPTION
**Pull request by keithdmoore**
add cordova-network-information plugin

### CODE REVIEW

**Comment by keithdmoore** [comment]
@mlynch @tlancina  I thought I had committer access to this repo.  Maybe I only have committer access to the ngCordova repo.  Would you or Tim mind giving me committer access to ionic-native?

**Comment by ihadeed** [comment]
Thanks for the PR @keithdmoore 

1. No need to import the `Connection` interface into `index.ts`
2. The plugin hasn't been added yet. I'm working on it in the `add-network-info` branch here: https://github.com/driftyco/ionic-native/blob/add-network-info/src/plugins/networkinformation.ts

**Comment by mlynch** [comment]
@keithdmoore done!

**Comment by ihadeed** [comment]
Never mind my previous comment. Just saw your recent commit @keithdmoore

**Comment by keithdmoore** [comment]
@mlynch Thanks!  
@ihadeed Sorry, I must have missed the fact that there was already an issue opened for this.  I implemented it fully.  Unless you disagree with my implementation, can we pull it in?

**Comment by ihadeed** [comment]
@keithdmoore 

Shouldn't `static get connection()` be `static get type()` to match the original plugin?

**Comment by keithdmoore** [comment]
@ihadeed I can change that if you want.  I went back and forth on that.  I did deviate a little with the event handlers.  onConnect and onDisconnect seemed to make more sense to me.  onOnline and onOffline sound and look weird.

**Comment by ihadeed** [comment]
@keithdmoore Yeah `onOnline` does sound weird. 

The reason I said change it to `type` because AFAIK the @CordovaProperty overrides the return value you have there by using the property name. 
Reference: https://github.com/driftyco/ionic-native/blob/master/src/plugins/plugin.ts#L240-L259

**Comment by keithdmoore** [comment]
@ihadeed I am having trouble getting `type` to work.  Were you able to get `type` to work?  My committed code works with the usage examples in an app I am working on.

**Comment by ihadeed** [comment]
@keithdmoore Ahh. `type` could be a reserved word.

If the code you wrote works then I think that's fine. I just thought the `@CordovaProperty` would overwrite it. I guess it's just there to check if the plugin and Cordova exist.

**Comment by ihadeed** [comment]
closes https://github.com/driftyco/ionic-native/issues/74

**Comment by keithdmoore** [comment]
@ihadeed Fair enough.  I just realized I left a comment that should be removed.  Ugggg.

**Comment by ihadeed** [comment]
@keithdmoore this one https://github.com/driftyco/ionic-native/commit/ed14d877226f38ed0742d1ed36d9f81de6ab0e04 ?

**Comment by keithdmoore** [comment]
@mlynch Looks like you gave the ngCordova team (which I am on) "read" access to ionic-native.

**Comment by ihadeed** [comment]
@keithdmoore @mlynch your input is appreciated here https://github.com/driftyco/ionic-native/issues/86

**Pull request merged**
